name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_n_lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cargo build
      run: cargo build --verbose
    - name: cargo clippy
      run: cargo clippy --verbose
    
  functional_test:
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: cargo test
      run: cargo test --verbose
